# Generated by Django 5.2.10 on 2026-01-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="song",
            constraint=models.UniqueConstraint(
                fields=("title", "audio_file"), name="unique_song_title_audio"
            ),
        ),
    ]
