# Generated by Django 5.2.10 on 2026-01-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_song_unique_song_title_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="lyrics_file",
            field=models.FileField(blank=True, upload_to="lyrics/"),
        ),
    ]
